# coding: utf-8

# flake8: noqa
"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from falaai_api.models.audio_event import AudioEvent
from falaai_api.models.audio_input_meta import AudioInputMeta
from falaai_api.models.create_email_alert_request import CreateEmailAlertRequest
from falaai_api.models.create_webhook_request import CreateWebhookRequest
from falaai_api.models.diagnostic_analysis_map import DiagnosticAnalysisMap
from falaai_api.models.diagnostic_audio_event import DiagnosticAudioEvent
from falaai_api.models.diagnostic_categorical_analysis import DiagnosticCategoricalAnalysis
from falaai_api.models.diagnostic_participant import DiagnosticParticipant
from falaai_api.models.diagnostic_request import DiagnosticRequest
from falaai_api.models.diagnostic_response import DiagnosticResponse
from falaai_api.models.diagnostic_text_analysis import DiagnosticTextAnalysis
from falaai_api.models.diagnostic_usage import DiagnosticUsage
from falaai_api.models.email_alert_item import EmailAlertItem
from falaai_api.models.email_alert_list_response import EmailAlertListResponse
from falaai_api.models.email_alert_message_response import EmailAlertMessageResponse
from falaai_api.models.email_event import EmailEvent
from falaai_api.models.http_validation_error import HTTPValidationError
from falaai_api.models.health_response import HealthResponse
from falaai_api.models.location_inner import LocationInner
from falaai_api.models.message_response import MessageResponse
from falaai_api.models.participant import Participant
from falaai_api.models.participant_diagnostic import ParticipantDiagnostic
from falaai_api.models.risk_audit_analysis_v2 import RiskAuditAnalysisV2
from falaai_api.models.risk_audit_applied_action_v2 import RiskAuditAppliedActionV2
from falaai_api.models.risk_audit_audio_event_model_v2 import RiskAuditAudioEventModelV2
from falaai_api.models.risk_audit_audit_decisions_v2 import RiskAuditAuditDecisionsV2
from falaai_api.models.risk_audit_conversation_scores_v2 import RiskAuditConversationScoresV2
from falaai_api.models.risk_audit_detection_item_v2 import RiskAuditDetectionItemV2
from falaai_api.models.risk_audit_detections_v2 import RiskAuditDetectionsV2
from falaai_api.models.risk_audit_indexer_v2 import RiskAuditIndexerV2
from falaai_api.models.risk_audit_meta_v2 import RiskAuditMetaV2
from falaai_api.models.risk_audit_participant_v2 import RiskAuditParticipantV2
from falaai_api.models.risk_audit_participants_v2 import RiskAuditParticipantsV2
from falaai_api.models.risk_audit_request import RiskAuditRequest
from falaai_api.models.risk_audit_scores_v2 import RiskAuditScoresV2
from falaai_api.models.risk_audit_scoring_explanation_v2 import RiskAuditScoringExplanationV2
from falaai_api.models.risk_audit_summary_v2 import RiskAuditSummaryV2
from falaai_api.models.risk_audit_timeline_v2 import RiskAuditTimelineV2
from falaai_api.models.risk_audit_usage_v2 import RiskAuditUsageV2
from falaai_api.models.risk_audit_v2 import RiskAuditV2
from falaai_api.models.risk_audit_v2_response import RiskAuditV2Response
from falaai_api.models.risk_audit_verdict_v2 import RiskAuditVerdictV2
from falaai_api.models.transcription_response import TranscriptionResponse
from falaai_api.models.transcription_usage import TranscriptionUsage
from falaai_api.models.update_email_alert_request import UpdateEmailAlertRequest
from falaai_api.models.update_webhook_request import UpdateWebhookRequest
from falaai_api.models.usage_by_key_item import UsageByKeyItem
from falaai_api.models.usage_log_item import UsageLogItem
from falaai_api.models.usage_log_response import UsageLogResponse
from falaai_api.models.validation_error import ValidationError
from falaai_api.models.version_response import VersionResponse
from falaai_api.models.webhook_event import WebhookEvent
from falaai_api.models.webhook_item import WebhookItem
from falaai_api.models.webhook_list_response import WebhookListResponse
from falaai_api.models.whatsapp_conversation import WhatsappConversation
from falaai_api.models.whatsapp_conversations_response import WhatsappConversationsResponse
from falaai_api.models.whatsapp_meta import WhatsappMeta
from falaai_api.models.whatsapp_speaker import WhatsappSpeaker
from falaai_api.models.whatsapp_usage import WhatsappUsage

