# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from falaai_api.models.webhook_event import WebhookEvent
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateWebhookRequest(BaseModel):
    """
    CreateWebhookRequest
    """ # noqa: E501
    name: StrictStr = Field(description="Nome identificador do webhook")
    url: StrictStr = Field(description="URL HTTPS que recebera POST com HMAC FalaAI-Signature")
    events: List[WebhookEvent] = Field(description="Eventos subscritos (10 alertas)")
    retry_enabled: Optional[StrictBool] = Field(default=False, description="Retry exponencial 5 tentativas quando true (false=1 tentativa)")
    __properties: ClassVar[List[str]] = ["name", "url", "events", "retry_enabled"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateWebhookRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateWebhookRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "url": obj.get("url"),
            "events": obj.get("events"),
            "retry_enabled": obj.get("retry_enabled") if obj.get("retry_enabled") is not None else False
        })
        return _obj


