# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.49
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from falaai_api.models.diagnostic_audio_event import DiagnosticAudioEvent
from falaai_api.models.diagnostic_participant import DiagnosticParticipant
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DiagnosticRequest(BaseModel):
    """
    DiagnosticRequest
    """ # noqa: E501
    model: Optional[StrictStr] = Field(default='falaai-diagnostic-1', description="Analysis model. Always 'falaai-diagnostic-1'")
    text: Optional[Annotated[str, Field(strict=True, max_length=300000)]] = Field(default='', description="Plain transcript (fallback if dialog is empty). At least one of 'dialog' or 'text' required. Max 300,000 characters")
    dialog: Optional[Annotated[str, Field(strict=True, max_length=300000)]] = Field(default='', description="Diarized transcript with speaker turns. PRIMARY source. At least one of 'dialog' or 'text' required. Speaker labels accepted (any case): 'Speaker N', 'Interlocutor N', 'Hablante N', 'Locutor N', 'Orador N' (space or underscore). Normalized internally to 'Speaker N' in the response. Max 300,000 characters")
    audio_events: Optional[Annotated[List[DiagnosticAudioEvent], Field(max_length=500)]] = Field(default=None, description="Detected audio events with timestamps (required when using dialog)")
    language: StrictStr = Field(description="Transcript language. Required. Accepted: en-US, pt-BR, es-ES, es-MX, fr-FR, de-DE, it-IT, pt-PT, zh-CN, ja-JP, ko-KR, ar-SA, hi-IN, ru-RU, id-ID, tr-TR, nl-NL, pl-PL, vi-VN, th-TH, en-GB")
    response_language: Optional[StrictStr] = Field(default=None, description="Language for the analysis results (labels, categories, levels). Can differ from 'language' (input). If omitted, uses 'language'. Accepted: en-US, es-ES, es-MX, pt-BR, fr-FR, de-DE, it-IT, pt-PT, zh-CN, ja-JP, ko-KR, ar-SA, hi-IN, ru-RU, id-ID, tr-TR, nl-NL, pl-PL, vi-VN, th-TH, en-GB.")
    duration_seconds: Union[Annotated[float, Field(strict=True, ge=1.0)], Annotated[int, Field(strict=True, ge=1)]] = Field(description="Total audio duration in seconds. Required. Max 3h (10800s).")
    client_reference_id: Optional[StrictStr] = Field(default=None, description="Optional client-supplied ID echoed verbatim in the response. Use to correlate/sync with your system. Accepted charset: [A-Za-z0-9._:-], max 128 chars. Not idempotency.")
    call_direction: Optional[StrictStr] = Field(default=None, description="Who originated the call. inbound=client called, outbound=company called. If omitted, the LLM infers from context.")
    participants: Optional[Annotated[List[DiagnosticParticipant], Field(max_length=10)]] = Field(default=None, description="Explicit participant roles. If omitted, the LLM infers from the dialog. When provided, used as ground truth (no inference) and echoed in analysis.participants_identified.")
    __properties: ClassVar[List[str]] = ["model", "text", "dialog", "audio_events", "language", "response_language", "duration_seconds", "client_reference_id", "call_direction", "participants"]

    @field_validator('call_direction')
    def call_direction_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['inbound', 'outbound']):
            raise ValueError("must be one of enum values ('inbound', 'outbound')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiagnosticRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in audio_events (list)
        _items = []
        if self.audio_events:
            for _item_audio_events in self.audio_events:
                _items.append(_item_audio_events.to_dict() if _item_audio_events is not None else None)
            _dict['audio_events'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in participants (list)
        _items = []
        if self.participants:
            for _item_participants in self.participants:
                _items.append(_item_participants.to_dict() if _item_participants is not None else None)
            _dict['participants'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiagnosticRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "model": obj.get("model") if obj.get("model") is not None else 'falaai-diagnostic-1',
            "text": obj.get("text") if obj.get("text") is not None else '',
            "dialog": obj.get("dialog") if obj.get("dialog") is not None else '',
            "audio_events": [DiagnosticAudioEvent.from_dict(_item) for _item in obj["audio_events"]] if obj.get("audio_events") is not None else None,
            "language": obj.get("language"),
            "response_language": obj.get("response_language"),
            "duration_seconds": obj.get("duration_seconds"),
            "client_reference_id": obj.get("client_reference_id"),
            "call_direction": obj.get("call_direction"),
            "participants": [DiagnosticParticipant.from_dict(_item) for _item in obj["participants"]] if obj.get("participants") is not None else None
        })
        return _obj


