# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.49
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from falaai_api.models.diagnostic_categorical_analysis import DiagnosticCategoricalAnalysis
from falaai_api.models.diagnostic_text_analysis import DiagnosticTextAnalysis
from falaai_api.models.participant_diagnostic import ParticipantDiagnostic
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DiagnosticAnalysisMap(BaseModel):
    """
    DiagnosticAnalysisMap
    """ # noqa: E501
    dialogue_summary: DiagnosticTextAnalysis = Field(description="Detailed conversation summary")
    contact_reason: DiagnosticTextAnalysis = Field(description="Initial contact reason")
    identified_action: DiagnosticCategoricalAnalysis = Field(description="Action taken / resolution")
    identified_label: DiagnosticCategoricalAnalysis = Field(description="Theme classification")
    sentiment: DiagnosticCategoricalAnalysis = Field(description="Predominant sentiment")
    participants_identified: Optional[List[ParticipantDiagnostic]] = Field(default=None, description="Identified participants and roles (same field names as auditoria)")
    __properties: ClassVar[List[str]] = ["dialogue_summary", "contact_reason", "identified_action", "identified_label", "sentiment", "participants_identified"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiagnosticAnalysisMap from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of dialogue_summary
        if self.dialogue_summary:
            _dict['dialogue_summary'] = self.dialogue_summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contact_reason
        if self.contact_reason:
            _dict['contact_reason'] = self.contact_reason.to_dict()
        # override the default output from pydantic by calling `to_dict()` of identified_action
        if self.identified_action:
            _dict['identified_action'] = self.identified_action.to_dict()
        # override the default output from pydantic by calling `to_dict()` of identified_label
        if self.identified_label:
            _dict['identified_label'] = self.identified_label.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sentiment
        if self.sentiment:
            _dict['sentiment'] = self.sentiment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in participants_identified (list)
        _items = []
        if self.participants_identified:
            for _item_participants_identified in self.participants_identified:
                _items.append(_item_participants_identified.to_dict() if _item_participants_identified is not None else None)
            _dict['participants_identified'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiagnosticAnalysisMap from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dialogue_summary": DiagnosticTextAnalysis.from_dict(obj["dialogue_summary"]) if obj.get("dialogue_summary") is not None else None,
            "contact_reason": DiagnosticTextAnalysis.from_dict(obj["contact_reason"]) if obj.get("contact_reason") is not None else None,
            "identified_action": DiagnosticCategoricalAnalysis.from_dict(obj["identified_action"]) if obj.get("identified_action") is not None else None,
            "identified_label": DiagnosticCategoricalAnalysis.from_dict(obj["identified_label"]) if obj.get("identified_label") is not None else None,
            "sentiment": DiagnosticCategoricalAnalysis.from_dict(obj["sentiment"]) if obj.get("sentiment") is not None else None,
            "participants_identified": [ParticipantDiagnostic.from_dict(_item) for _item in obj["participants_identified"]] if obj.get("participants_identified") is not None else None
        })
        return _obj


