# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.49
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EmailEvent(str, Enum):
    """
    EmailEvent
    """

    """
    allowed enum values
    """
    SUBSCRIPTION_DOT_CREATED = 'subscription.created'
    AVULSO_DOT_COMPLETED = 'avulso.completed'
    SUBSCRIPTION_DOT_UPGRADED = 'subscription.upgraded'
    SUBSCRIPTION_DOT_DOWNGRADED = 'subscription.downgraded'
    SUBSCRIPTION_DOT_CANCELED = 'subscription.canceled'
    CREDITS_DOT_LOW = 'credits.low'
    CREDITS_DOT_EXHAUSTED = 'credits.exhausted'
    SUBSCRIPTION_DOT_RENEWED = 'subscription.renewed'
    PAYMENT_DOT_FAILED = 'payment.failed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EmailEvent from a JSON string"""
        return cls(json.loads(json_str))


