# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.49
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RiskAuditConversationScoresV2(BaseModel):
    """
    RiskAuditConversationScoresV2
    """ # noqa: E501
    consolidated_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Consolidated score")
    violation_density_per_min: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Violation density/min")
    sentiment_trend: Optional[Any] = Field(default=None, description="Sentiment trend")
    pct_turns_with_violation: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="% turns with violation")
    most_critical_turn: Optional[Any] = Field(default=None, description="Most critical turn")
    positive_negative_ratio: Optional[Any] = Field(default=None, description="Positive:negative ratio")
    global_risk_severity: Optional[StrictStr] = Field(default=None, description="Global risk severity code")
    global_risk_severity_label: Optional[StrictStr] = Field(default=None, description="Global risk severity label")
    global_risk_severity_color: Optional[StrictStr] = Field(default=None, description="Global risk severity color")
    risk_likelihood_avg: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Risk likelihood avg")
    risk_impact_avg: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Risk impact avg")
    __properties: ClassVar[List[str]] = ["consolidated_score", "violation_density_per_min", "sentiment_trend", "pct_turns_with_violation", "most_critical_turn", "positive_negative_ratio", "global_risk_severity", "global_risk_severity_label", "global_risk_severity_color", "risk_likelihood_avg", "risk_impact_avg"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskAuditConversationScoresV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if sentiment_trend (nullable) is None
        # and model_fields_set contains the field
        if self.sentiment_trend is None and "sentiment_trend" in self.model_fields_set:
            _dict['sentiment_trend'] = None

        # set to None if most_critical_turn (nullable) is None
        # and model_fields_set contains the field
        if self.most_critical_turn is None and "most_critical_turn" in self.model_fields_set:
            _dict['most_critical_turn'] = None

        # set to None if positive_negative_ratio (nullable) is None
        # and model_fields_set contains the field
        if self.positive_negative_ratio is None and "positive_negative_ratio" in self.model_fields_set:
            _dict['positive_negative_ratio'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskAuditConversationScoresV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "consolidated_score": obj.get("consolidated_score"),
            "violation_density_per_min": obj.get("violation_density_per_min"),
            "sentiment_trend": obj.get("sentiment_trend"),
            "pct_turns_with_violation": obj.get("pct_turns_with_violation"),
            "most_critical_turn": obj.get("most_critical_turn"),
            "positive_negative_ratio": obj.get("positive_negative_ratio"),
            "global_risk_severity": obj.get("global_risk_severity"),
            "global_risk_severity_label": obj.get("global_risk_severity_label"),
            "global_risk_severity_color": obj.get("global_risk_severity_color"),
            "risk_likelihood_avg": obj.get("risk_likelihood_avg"),
            "risk_impact_avg": obj.get("risk_impact_avg")
        })
        return _obj


