# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.49
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RiskAuditDetectionItemV2(BaseModel):
    """
    RiskAuditDetectionItemV2
    """ # noqa: E501
    turn: Optional[StrictInt] = Field(default=None, description="Turn number")
    interlocutor: Optional[StrictStr] = Field(default=None, description="Speaker")
    role: Optional[StrictStr] = Field(default=None, description="Role")
    timestamp_start_s: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Start (s)")
    timestamp_end_s: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="End (s)")
    timestamp_formatted: Optional[StrictStr] = Field(default=None, description="Formatted timestamp")
    term_text: Optional[StrictStr] = Field(default=None, description="Detected term")
    suggested_term_for_bank: Optional[Any] = Field(default=None, description="Suggested term for bank")
    category: Optional[StrictStr] = Field(default=None, description="Category code")
    category_label: StrictStr = Field(description="Category label (i18n)")
    category_color: Optional[StrictStr] = Field(default=None, description="Category color")
    category_icon: Optional[StrictStr] = Field(default=None, description="Category icon")
    criticality: Optional[StrictStr] = Field(default=None, description="Criticality")
    category_threshold: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Category threshold")
    category_type: Optional[StrictStr] = Field(default=None, description="Category type")
    category_group: StrictStr = Field(description="Category group label (i18n)")
    nature: Optional[StrictStr] = Field(default=None, description="Nature")
    llm_confidence: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="LLM confidence")
    reason: Optional[StrictStr] = Field(default=None, description="Reason")
    is_valid_context: Optional[StrictBool] = Field(default=None, description="Valid context")
    risk_probability: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Risk probability")
    risk_impact: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Risk impact")
    category_weight: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Category weight")
    turn_sentiment: Optional[StrictStr] = Field(default=None, description="Turn sentiment")
    intensity: Optional[Any] = Field(default=None, description="Intensity")
    mod_applied: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Total modifier applied")
    mac_applied: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Audio modifier applied")
    mvad_applied: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Intensity modifier applied")
    mod_formula: Optional[StrictStr] = Field(default=None, description="Modifier formula")
    mac_details: Optional[List[Dict[str, Any]]] = Field(default=None, description="MAC details")
    calibration_reason: Optional[StrictStr] = Field(default=None, description="Calibration reason")
    final_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Final score")
    final_score_formula: Optional[StrictStr] = Field(default=None, description="Final score formula")
    conversation_limit: Optional[Any] = Field(default=None, description="Conversation limit")
    apply_saturation: Optional[StrictBool] = Field(default=None, description="Apply saturation")
    block_repetition: Optional[StrictBool] = Field(default=None, description="Block repetition")
    status: Optional[StrictStr] = Field(default=None, description="Status")
    effective_impact: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Effective impact")
    saturation_factor: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Saturation factor")
    saturation_formula: Optional[StrictStr] = Field(default=None, description="Saturation formula")
    threshold_formula: Optional[StrictStr] = Field(default=None, description="Threshold formula")
    blocked_formula: Optional[StrictStr] = Field(default=None, description="Blocked formula")
    reconciliation_note: Optional[StrictStr] = Field(default=None, description="Reconciliation note")
    violated_frameworks: Optional[List[Any]] = Field(default=None, description="Violated frameworks")
    citation_fidelity: Optional[StrictBool] = Field(default=True, description="Citation fidelity")
    subcategory: Optional[StrictStr] = Field(default=None, description="Subcategory code")
    subcategory_label: Optional[StrictStr] = Field(default=None, description="Subcategory label (i18n)")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["turn", "interlocutor", "role", "timestamp_start_s", "timestamp_end_s", "timestamp_formatted", "term_text", "suggested_term_for_bank", "category", "category_label", "category_color", "category_icon", "criticality", "category_threshold", "category_type", "category_group", "nature", "llm_confidence", "reason", "is_valid_context", "risk_probability", "risk_impact", "category_weight", "turn_sentiment", "intensity", "mod_applied", "mac_applied", "mvad_applied", "mod_formula", "mac_details", "calibration_reason", "final_score", "final_score_formula", "conversation_limit", "apply_saturation", "block_repetition", "status", "effective_impact", "saturation_factor", "saturation_formula", "threshold_formula", "blocked_formula", "reconciliation_note", "violated_frameworks", "citation_fidelity", "subcategory", "subcategory_label"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskAuditDetectionItemV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if suggested_term_for_bank (nullable) is None
        # and model_fields_set contains the field
        if self.suggested_term_for_bank is None and "suggested_term_for_bank" in self.model_fields_set:
            _dict['suggested_term_for_bank'] = None

        # set to None if intensity (nullable) is None
        # and model_fields_set contains the field
        if self.intensity is None and "intensity" in self.model_fields_set:
            _dict['intensity'] = None

        # set to None if conversation_limit (nullable) is None
        # and model_fields_set contains the field
        if self.conversation_limit is None and "conversation_limit" in self.model_fields_set:
            _dict['conversation_limit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskAuditDetectionItemV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "turn": obj.get("turn"),
            "interlocutor": obj.get("interlocutor"),
            "role": obj.get("role"),
            "timestamp_start_s": obj.get("timestamp_start_s"),
            "timestamp_end_s": obj.get("timestamp_end_s"),
            "timestamp_formatted": obj.get("timestamp_formatted"),
            "term_text": obj.get("term_text"),
            "suggested_term_for_bank": obj.get("suggested_term_for_bank"),
            "category": obj.get("category"),
            "category_label": obj.get("category_label"),
            "category_color": obj.get("category_color"),
            "category_icon": obj.get("category_icon"),
            "criticality": obj.get("criticality"),
            "category_threshold": obj.get("category_threshold"),
            "category_type": obj.get("category_type"),
            "category_group": obj.get("category_group"),
            "nature": obj.get("nature"),
            "llm_confidence": obj.get("llm_confidence"),
            "reason": obj.get("reason"),
            "is_valid_context": obj.get("is_valid_context"),
            "risk_probability": obj.get("risk_probability"),
            "risk_impact": obj.get("risk_impact"),
            "category_weight": obj.get("category_weight"),
            "turn_sentiment": obj.get("turn_sentiment"),
            "intensity": obj.get("intensity"),
            "mod_applied": obj.get("mod_applied"),
            "mac_applied": obj.get("mac_applied"),
            "mvad_applied": obj.get("mvad_applied"),
            "mod_formula": obj.get("mod_formula"),
            "mac_details": obj.get("mac_details"),
            "calibration_reason": obj.get("calibration_reason"),
            "final_score": obj.get("final_score"),
            "final_score_formula": obj.get("final_score_formula"),
            "conversation_limit": obj.get("conversation_limit"),
            "apply_saturation": obj.get("apply_saturation"),
            "block_repetition": obj.get("block_repetition"),
            "status": obj.get("status"),
            "effective_impact": obj.get("effective_impact"),
            "saturation_factor": obj.get("saturation_factor"),
            "saturation_formula": obj.get("saturation_formula"),
            "threshold_formula": obj.get("threshold_formula"),
            "blocked_formula": obj.get("blocked_formula"),
            "reconciliation_note": obj.get("reconciliation_note"),
            "violated_frameworks": obj.get("violated_frameworks"),
            "citation_fidelity": obj.get("citation_fidelity") if obj.get("citation_fidelity") is not None else True,
            "subcategory": obj.get("subcategory"),
            "subcategory_label": obj.get("subcategory_label")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


