# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.49
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from falaai_api.models.risk_audit_detection_item_v2 import RiskAuditDetectionItemV2
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RiskAuditDetectionsV2(BaseModel):
    """
    RiskAuditDetectionsV2
    """ # noqa: E501
    violations: Optional[List[RiskAuditDetectionItemV2]] = Field(default=None, description="Active violations")
    positives: Optional[List[RiskAuditDetectionItemV2]] = Field(default=None, description="Active positives")
    client_risk_alerts: Optional[List[Dict[str, Any]]] = Field(default=None, description="Client risk alerts")
    client_behavior_alerts: Optional[List[Dict[str, Any]]] = Field(default=None, description="Client behavior alerts")
    client_negatives: Optional[List[RiskAuditDetectionItemV2]] = Field(default=None, description="Client negatives")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["violations", "positives", "client_risk_alerts", "client_behavior_alerts", "client_negatives"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskAuditDetectionsV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in violations (list)
        _items = []
        if self.violations:
            for _item_violations in self.violations:
                _items.append(_item_violations.to_dict() if _item_violations is not None else None)
            _dict['violations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in positives (list)
        _items = []
        if self.positives:
            for _item_positives in self.positives:
                _items.append(_item_positives.to_dict() if _item_positives is not None else None)
            _dict['positives'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in client_negatives (list)
        _items = []
        if self.client_negatives:
            for _item_client_negatives in self.client_negatives:
                _items.append(_item_client_negatives.to_dict() if _item_client_negatives is not None else None)
            _dict['client_negatives'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskAuditDetectionsV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "violations": [RiskAuditDetectionItemV2.from_dict(_item) for _item in obj["violations"]] if obj.get("violations") is not None else None,
            "positives": [RiskAuditDetectionItemV2.from_dict(_item) for _item in obj["positives"]] if obj.get("positives") is not None else None,
            "client_risk_alerts": obj.get("client_risk_alerts"),
            "client_behavior_alerts": obj.get("client_behavior_alerts"),
            "client_negatives": [RiskAuditDetectionItemV2.from_dict(_item) for _item in obj["client_negatives"]] if obj.get("client_negatives") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


