# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RiskAuditSummaryV2(BaseModel):
    """
    RiskAuditSummaryV2
    """ # noqa: E501
    total_turns: Optional[StrictInt] = Field(default=None, description="Total turns")
    total_calibrated: Optional[StrictInt] = Field(default=None, description="Total calibrated detections")
    active: Optional[StrictInt] = Field(default=None, description="Active detections")
    tolerated: Optional[StrictInt] = Field(default=None, description="Tolerated detections")
    blocked: Optional[StrictInt] = Field(default=None, description="Blocked detections")
    audio_events_used: Optional[StrictInt] = Field(default=None, description="Audio events used")
    audio_events_aggravated: Optional[StrictInt] = Field(default=None, description="Audio events aggravated")
    mac_audio_applied: Optional[Any] = Field(default=None, description="MAC audio applied")
    mvad_applied: Optional[Any] = Field(default=None, description="MVAD applied")
    total_participants: Optional[StrictInt] = Field(default=None, description="Total participants")
    total_agents: Optional[StrictInt] = Field(default=None, description="Total agents")
    total_clients: Optional[StrictInt] = Field(default=None, description="Total clients")
    total_bots: Optional[StrictInt] = Field(default=None, description="Total bots")
    total_unknown: Optional[StrictInt] = Field(default=None, description="Total unknown")
    client_risk_alerts_count: Optional[StrictInt] = Field(default=None, description="Client risk alerts count")
    client_behavior_alerts_count: Optional[StrictInt] = Field(default=None, description="Client behavior alerts count")
    __properties: ClassVar[List[str]] = ["total_turns", "total_calibrated", "active", "tolerated", "blocked", "audio_events_used", "audio_events_aggravated", "mac_audio_applied", "mvad_applied", "total_participants", "total_agents", "total_clients", "total_bots", "total_unknown", "client_risk_alerts_count", "client_behavior_alerts_count"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskAuditSummaryV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if mac_audio_applied (nullable) is None
        # and model_fields_set contains the field
        if self.mac_audio_applied is None and "mac_audio_applied" in self.model_fields_set:
            _dict['mac_audio_applied'] = None

        # set to None if mvad_applied (nullable) is None
        # and model_fields_set contains the field
        if self.mvad_applied is None and "mvad_applied" in self.model_fields_set:
            _dict['mvad_applied'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskAuditSummaryV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_turns": obj.get("total_turns"),
            "total_calibrated": obj.get("total_calibrated"),
            "active": obj.get("active"),
            "tolerated": obj.get("tolerated"),
            "blocked": obj.get("blocked"),
            "audio_events_used": obj.get("audio_events_used"),
            "audio_events_aggravated": obj.get("audio_events_aggravated"),
            "mac_audio_applied": obj.get("mac_audio_applied"),
            "mvad_applied": obj.get("mvad_applied"),
            "total_participants": obj.get("total_participants"),
            "total_agents": obj.get("total_agents"),
            "total_clients": obj.get("total_clients"),
            "total_bots": obj.get("total_bots"),
            "total_unknown": obj.get("total_unknown"),
            "client_risk_alerts_count": obj.get("client_risk_alerts_count"),
            "client_behavior_alerts_count": obj.get("client_behavior_alerts_count")
        })
        return _obj


