# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from falaai_api.models.risk_audit_analysis_v2 import RiskAuditAnalysisV2
from falaai_api.models.risk_audit_audio_event_model_v2 import RiskAuditAudioEventModelV2
from falaai_api.models.risk_audit_audit_decisions_v2 import RiskAuditAuditDecisionsV2
from falaai_api.models.risk_audit_detections_v2 import RiskAuditDetectionsV2
from falaai_api.models.risk_audit_indexer_v2 import RiskAuditIndexerV2
from falaai_api.models.risk_audit_meta_v2 import RiskAuditMetaV2
from falaai_api.models.risk_audit_participants_v2 import RiskAuditParticipantsV2
from falaai_api.models.risk_audit_scores_v2 import RiskAuditScoresV2
from falaai_api.models.risk_audit_scoring_explanation_v2 import RiskAuditScoringExplanationV2
from falaai_api.models.risk_audit_summary_v2 import RiskAuditSummaryV2
from falaai_api.models.risk_audit_timeline_v2 import RiskAuditTimelineV2
from falaai_api.models.risk_audit_verdict_v2 import RiskAuditVerdictV2
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RiskAuditV2(BaseModel):
    """
    Response V2 (build_public_response_v2) — blocos logicos EN-US. Fonte: response_builder.py.
    """ # noqa: E501
    meta: RiskAuditMetaV2 = Field(description="Identification + usage")
    participants: RiskAuditParticipantsV2 = Field(description="Participants/roles/direction")
    verdict: RiskAuditVerdictV2 = Field(description="Verdict + level + applied actions")
    scores: RiskAuditScoresV2 = Field(description="Consolidated + per-participant scores")
    detections: RiskAuditDetectionsV2 = Field(description="violations/positives/client alerts")
    analysis: RiskAuditAnalysisV2 = Field(description="global_metrics + final_analysis + frameworks")
    timeline: RiskAuditTimelineV2 = Field(description="turns_sentiment + audio_events + groups")
    audio_event_model: RiskAuditAudioEventModelV2 = Field(description="MAC audio event semantics")
    categories_summary: Dict[str, Any] = Field(description="Per-category summary (keyed by category)")
    indexer: RiskAuditIndexerV2 = Field(description="Suggested terms for bank")
    summary: RiskAuditSummaryV2 = Field(description="Executive summary counts")
    actions_i18n: Dict[str, Any] = Field(description="Used actions i18n catalog (keyed by action)")
    audit_decisions: RiskAuditAuditDecisionsV2 = Field(description="Risk origin + validator changes")
    scoring_explanation: RiskAuditScoringExplanationV2 = Field(description="Score composition explanation")
    html_report: StrictStr = Field(description="HTML report (base64 gzip)")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["meta", "participants", "verdict", "scores", "detections", "analysis", "timeline", "audio_event_model", "categories_summary", "indexer", "summary", "actions_i18n", "audit_decisions", "scoring_explanation", "html_report"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskAuditV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of participants
        if self.participants:
            _dict['participants'] = self.participants.to_dict()
        # override the default output from pydantic by calling `to_dict()` of verdict
        if self.verdict:
            _dict['verdict'] = self.verdict.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scores
        if self.scores:
            _dict['scores'] = self.scores.to_dict()
        # override the default output from pydantic by calling `to_dict()` of detections
        if self.detections:
            _dict['detections'] = self.detections.to_dict()
        # override the default output from pydantic by calling `to_dict()` of analysis
        if self.analysis:
            _dict['analysis'] = self.analysis.to_dict()
        # override the default output from pydantic by calling `to_dict()` of timeline
        if self.timeline:
            _dict['timeline'] = self.timeline.to_dict()
        # override the default output from pydantic by calling `to_dict()` of audio_event_model
        if self.audio_event_model:
            _dict['audio_event_model'] = self.audio_event_model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of indexer
        if self.indexer:
            _dict['indexer'] = self.indexer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of audit_decisions
        if self.audit_decisions:
            _dict['audit_decisions'] = self.audit_decisions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scoring_explanation
        if self.scoring_explanation:
            _dict['scoring_explanation'] = self.scoring_explanation.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskAuditV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "meta": RiskAuditMetaV2.from_dict(obj["meta"]) if obj.get("meta") is not None else None,
            "participants": RiskAuditParticipantsV2.from_dict(obj["participants"]) if obj.get("participants") is not None else None,
            "verdict": RiskAuditVerdictV2.from_dict(obj["verdict"]) if obj.get("verdict") is not None else None,
            "scores": RiskAuditScoresV2.from_dict(obj["scores"]) if obj.get("scores") is not None else None,
            "detections": RiskAuditDetectionsV2.from_dict(obj["detections"]) if obj.get("detections") is not None else None,
            "analysis": RiskAuditAnalysisV2.from_dict(obj["analysis"]) if obj.get("analysis") is not None else None,
            "timeline": RiskAuditTimelineV2.from_dict(obj["timeline"]) if obj.get("timeline") is not None else None,
            "audio_event_model": RiskAuditAudioEventModelV2.from_dict(obj["audio_event_model"]) if obj.get("audio_event_model") is not None else None,
            "categories_summary": obj.get("categories_summary"),
            "indexer": RiskAuditIndexerV2.from_dict(obj["indexer"]) if obj.get("indexer") is not None else None,
            "summary": RiskAuditSummaryV2.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "actions_i18n": obj.get("actions_i18n"),
            "audit_decisions": RiskAuditAuditDecisionsV2.from_dict(obj["audit_decisions"]) if obj.get("audit_decisions") is not None else None,
            "scoring_explanation": RiskAuditScoringExplanationV2.from_dict(obj["scoring_explanation"]) if obj.get("scoring_explanation") is not None else None,
            "html_report": obj.get("html_report")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


