# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from falaai_api.models.risk_audit_participant_v2 import RiskAuditParticipantV2
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RiskAuditParticipantsV2(BaseModel):
    """
    RiskAuditParticipantsV2
    """ # noqa: E501
    identified: Optional[List[RiskAuditParticipantV2]] = Field(default=None, description="Identified participants")
    call_direction: Optional[StrictStr] = Field(default=None, description="inbound/outbound")
    role_inference_reliable: Optional[StrictBool] = Field(default=True, description="Role inference reliability")
    identification_status: Optional[StrictStr] = Field(default='none', description="Identification status")
    unidentified_items_count: Optional[StrictInt] = Field(default=0, description="Unidentified items count")
    __properties: ClassVar[List[str]] = ["identified", "call_direction", "role_inference_reliable", "identification_status", "unidentified_items_count"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskAuditParticipantsV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in identified (list)
        _items = []
        if self.identified:
            for _item_identified in self.identified:
                _items.append(_item_identified.to_dict() if _item_identified is not None else None)
            _dict['identified'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskAuditParticipantsV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identified": [RiskAuditParticipantV2.from_dict(_item) for _item in obj["identified"]] if obj.get("identified") is not None else None,
            "call_direction": obj.get("call_direction"),
            "role_inference_reliable": obj.get("role_inference_reliable") if obj.get("role_inference_reliable") is not None else True,
            "identification_status": obj.get("identification_status") if obj.get("identification_status") is not None else 'none',
            "unidentified_items_count": obj.get("unidentified_items_count") if obj.get("unidentified_items_count") is not None else 0
        })
        return _obj


