# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from falaai_api.models.audio_event import AudioEvent
from falaai_api.models.audio_input_meta import AudioInputMeta
from falaai_api.models.transcription_usage import TranscriptionUsage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TranscriptionResponse(BaseModel):
    """
    TranscriptionResponse
    """ # noqa: E501
    id: StrictStr = Field(description="Unique transcription identifier. Prefix 'tr-' followed by UUID")
    object: StrictStr = Field(description="Returned object type. Always 'transcription'")
    model: StrictStr = Field(description="Model used for transcription. Ex: 'falaai-transcribe-1'")
    filename: StrictStr = Field(description="Original audio file name uploaded")
    processed_at: StrictStr = Field(description="Processing datetime in ISO 8601 UTC format")
    usage: TranscriptionUsage = Field(description="Usage and processing information")
    language: StrictStr = Field(description="ISO 639-3 language code detected in audio. Ex: 'por' (Portuguese), 'eng' (English), 'spa' (Spanish)")
    language_confidence: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Language detection confidence level (0.0 to 1.0). Higher is more reliable")
    duration_seconds: Union[StrictFloat, StrictInt] = Field(description="Total audio duration in seconds")
    text: StrictStr = Field(description="Full transcription as plain text, including audio events in brackets")
    dialog: StrictStr = Field(description="Turn-by-turn formatted transcript with speaker identification and start/end timestamps")
    audio_events: List[AudioEvent] = Field(description="List of detected audio events (laughs, sighs, pauses, etc) with timestamps and duration")
    event_types: List[StrictStr] = Field(description="Unique audio event types found in transcription, alphabetically sorted")
    word_count: StrictInt = Field(description="Total number of recognized words in transcription")
    input: AudioInputMeta = Field(description="Metadados do arquivo de audio enviado (duracao, formato, codec, sample rate, canais)")
    client_reference_id: Optional[StrictStr] = Field(default=None, description="Client-supplied ID echoed verbatim (if provided in request)")
    __properties: ClassVar[List[str]] = ["id", "object", "model", "filename", "processed_at", "usage", "language", "language_confidence", "duration_seconds", "text", "dialog", "audio_events", "event_types", "word_count", "input", "client_reference_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TranscriptionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in audio_events (list)
        _items = []
        if self.audio_events:
            for _item_audio_events in self.audio_events:
                _items.append(_item_audio_events.to_dict() if _item_audio_events is not None else None)
            _dict['audio_events'] = _items
        # override the default output from pydantic by calling `to_dict()` of input
        if self.input:
            _dict['input'] = self.input.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TranscriptionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "model": obj.get("model"),
            "filename": obj.get("filename"),
            "processed_at": obj.get("processed_at"),
            "usage": TranscriptionUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
            "language": obj.get("language"),
            "language_confidence": obj.get("language_confidence"),
            "duration_seconds": obj.get("duration_seconds"),
            "text": obj.get("text"),
            "dialog": obj.get("dialog"),
            "audio_events": [AudioEvent.from_dict(_item) for _item in obj["audio_events"]] if obj.get("audio_events") is not None else None,
            "event_types": obj.get("event_types"),
            "word_count": obj.get("word_count"),
            "input": AudioInputMeta.from_dict(obj["input"]) if obj.get("input") is not None else None,
            "client_reference_id": obj.get("client_reference_id")
        })
        return _obj


