# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WebhookItem(BaseModel):
    """
    WebhookItem
    """ # noqa: E501
    id: StrictStr = Field(description="Webhook id")
    user_id: StrictStr = Field(description="Owner user id")
    name: StrictStr = Field(description="Webhook name")
    url: StrictStr = Field(description="Destination URL")
    secret: StrictStr = Field(description="HMAC signing secret")
    events: List[StrictStr] = Field(description="Subscribed events")
    active: StrictBool = Field(description="Is active")
    retry_enabled: StrictBool = Field(description="Retry enabled")
    last_delivery_at: Optional[StrictStr] = Field(default=None, description="ISO 8601 of last delivery")
    last_status: Optional[StrictInt] = Field(default=None, description="Last HTTP status delivered")
    failure_count: Optional[StrictInt] = Field(default=0, description="Consecutive failures")
    created_at: StrictStr = Field(description="ISO 8601 created")
    updated_at: StrictStr = Field(description="ISO 8601 updated")
    __properties: ClassVar[List[str]] = ["id", "user_id", "name", "url", "secret", "events", "active", "retry_enabled", "last_delivery_at", "last_status", "failure_count", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "user_id": obj.get("user_id"),
            "name": obj.get("name"),
            "url": obj.get("url"),
            "secret": obj.get("secret"),
            "events": obj.get("events"),
            "active": obj.get("active"),
            "retry_enabled": obj.get("retry_enabled"),
            "last_delivery_at": obj.get("last_delivery_at"),
            "last_status": obj.get("last_status"),
            "failure_count": obj.get("failure_count") if obj.get("failure_count") is not None else 0,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


