# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WhatsappMeta(BaseModel):
    """
    WhatsappMeta
    """ # noqa: E501
    file: StrictStr = Field(description="Uploaded file name")
    chat_txt: StrictStr = Field(description="chat.txt entry name inside the export")
    format: StrictStr = Field(description="Detected format: Android | iOS")
    date_format: StrictStr = Field(description="Date order used")
    timezone: StrictStr = Field(description="Timezone informed")
    start: StrictStr = Field(description="Window start (ISO)")
    end: StrictStr = Field(description="Window end (ISO)")
    gap_minutes: Union[StrictFloat, StrictInt] = Field(description="Gap used to split conversations")
    min_messages: StrictInt = Field(description="Minimum messages per conversation")
    chars_per_minute: Union[StrictFloat, StrictInt] = Field(description="Chars per minute used to estimate duration")
    turns: StrictInt = Field(description="Total parsed turns")
    system_lines: StrictInt = Field(description="System lines ignored")
    conversations_total: StrictInt = Field(description="Conversations before window filter")
    conversations_in_window: StrictInt = Field(description="Conversations overlapping the window")
    monologues_dropped: StrictInt = Field(description="Single-speaker conversations dropped")
    conversations_selected: StrictInt = Field(description="Final conversations returned")
    __properties: ClassVar[List[str]] = ["file", "chat_txt", "format", "date_format", "timezone", "start", "end", "gap_minutes", "min_messages", "chars_per_minute", "turns", "system_lines", "conversations_total", "conversations_in_window", "monologues_dropped", "conversations_selected"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WhatsappMeta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WhatsappMeta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "file": obj.get("file"),
            "chat_txt": obj.get("chat_txt"),
            "format": obj.get("format"),
            "date_format": obj.get("date_format"),
            "timezone": obj.get("timezone"),
            "start": obj.get("start"),
            "end": obj.get("end"),
            "gap_minutes": obj.get("gap_minutes"),
            "min_messages": obj.get("min_messages"),
            "chars_per_minute": obj.get("chars_per_minute"),
            "turns": obj.get("turns"),
            "system_lines": obj.get("system_lines"),
            "conversations_total": obj.get("conversations_total"),
            "conversations_in_window": obj.get("conversations_in_window"),
            "monologues_dropped": obj.get("monologues_dropped"),
            "conversations_selected": obj.get("conversations_selected")
        })
        return _obj


