# coding: utf-8

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from falaai_api.models.whatsapp_speaker import WhatsappSpeaker
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WhatsappConversation(BaseModel):
    """
    WhatsappConversation
    """ # noqa: E501
    conversation_id: StrictStr = Field(description="Conversation identifier in the batch")
    first_at: StrictStr = Field(description="Real start (wall-clock, ISO)")
    last_at: StrictStr = Field(description="Real end (wall-clock, ISO)")
    duration_seconds: Union[StrictFloat, StrictInt] = Field(description="(last - first) + last turn duration")
    speakers: List[WhatsappSpeaker] = Field(description="Speakers of THIS conversation (dynamic)")
    dialog: StrictStr = Field(description="Lines 'Speaker N: [HH:MM:SS.mmm - HH:MM:SS.mmm] text' (real offset)")
    message_count: StrictInt = Field(description="Number of messages")
    characters: StrictInt = Field(description="Total characters of the conversation")
    __properties: ClassVar[List[str]] = ["conversation_id", "first_at", "last_at", "duration_seconds", "speakers", "dialog", "message_count", "characters"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WhatsappConversation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in speakers (list)
        _items = []
        if self.speakers:
            for _item_speakers in self.speakers:
                _items.append(_item_speakers.to_dict() if _item_speakers is not None else None)
            _dict['speakers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WhatsappConversation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conversation_id": obj.get("conversation_id"),
            "first_at": obj.get("first_at"),
            "last_at": obj.get("last_at"),
            "duration_seconds": obj.get("duration_seconds"),
            "speakers": [WhatsappSpeaker.from_dict(_item) for _item in obj["speakers"]] if obj.get("speakers") is not None else None,
            "dialog": obj.get("dialog"),
            "message_count": obj.get("message_count"),
            "characters": obj.get("characters")
        })
        return _obj


