# coding: utf-8

# flake8: noqa

"""
    FalaAI API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.21.51
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AnalysisApi",
    "EmailAlertsApi",
    "HealthApi",
    "SpeechApi",
    "UsageApi",
    "VersionApi",
    "WebhooksApi",
    "WhatsappApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AudioEvent",
    "AudioInputMeta",
    "CreateEmailAlertRequest",
    "CreateWebhookRequest",
    "DiagnosticAnalysisMap",
    "DiagnosticAudioEvent",
    "DiagnosticCategoricalAnalysis",
    "DiagnosticParticipant",
    "DiagnosticRequest",
    "DiagnosticResponse",
    "DiagnosticTextAnalysis",
    "DiagnosticUsage",
    "EmailAlertItem",
    "EmailAlertListResponse",
    "EmailAlertMessageResponse",
    "EmailEvent",
    "HTTPValidationError",
    "HealthResponse",
    "LocationInner",
    "MessageResponse",
    "Participant",
    "ParticipantDiagnostic",
    "RiskAuditAnalysisV2",
    "RiskAuditAppliedActionV2",
    "RiskAuditAudioEventModelV2",
    "RiskAuditAuditDecisionsV2",
    "RiskAuditConversationScoresV2",
    "RiskAuditDetectionItemV2",
    "RiskAuditDetectionsV2",
    "RiskAuditIndexerV2",
    "RiskAuditMetaV2",
    "RiskAuditParticipantV2",
    "RiskAuditParticipantsV2",
    "RiskAuditRequest",
    "RiskAuditScoresV2",
    "RiskAuditScoringExplanationV2",
    "RiskAuditSummaryV2",
    "RiskAuditTimelineV2",
    "RiskAuditUsageV2",
    "RiskAuditV2",
    "RiskAuditV2Response",
    "RiskAuditVerdictV2",
    "TranscriptionResponse",
    "TranscriptionUsage",
    "UpdateEmailAlertRequest",
    "UpdateWebhookRequest",
    "UsageByKeyItem",
    "UsageLogItem",
    "UsageLogResponse",
    "ValidationError",
    "VersionResponse",
    "WebhookEvent",
    "WebhookItem",
    "WebhookListResponse",
    "WhatsappConversation",
    "WhatsappConversationsResponse",
    "WhatsappMeta",
    "WhatsappSpeaker",
    "WhatsappUsage",
]

# import apis into sdk package
from falaai_api.api.analysis_api import AnalysisApi as AnalysisApi
from falaai_api.api.email_alerts_api import EmailAlertsApi as EmailAlertsApi
from falaai_api.api.health_api import HealthApi as HealthApi
from falaai_api.api.speech_api import SpeechApi as SpeechApi
from falaai_api.api.usage_api import UsageApi as UsageApi
from falaai_api.api.version_api import VersionApi as VersionApi
from falaai_api.api.webhooks_api import WebhooksApi as WebhooksApi
from falaai_api.api.whatsapp_api import WhatsappApi as WhatsappApi

# import ApiClient
from falaai_api.api_response import ApiResponse as ApiResponse
from falaai_api.api_client import ApiClient as ApiClient
from falaai_api.configuration import Configuration as Configuration
from falaai_api.exceptions import OpenApiException as OpenApiException
from falaai_api.exceptions import ApiTypeError as ApiTypeError
from falaai_api.exceptions import ApiValueError as ApiValueError
from falaai_api.exceptions import ApiKeyError as ApiKeyError
from falaai_api.exceptions import ApiAttributeError as ApiAttributeError
from falaai_api.exceptions import ApiException as ApiException

# import models into sdk package
from falaai_api.models.audio_event import AudioEvent as AudioEvent
from falaai_api.models.audio_input_meta import AudioInputMeta as AudioInputMeta
from falaai_api.models.create_email_alert_request import CreateEmailAlertRequest as CreateEmailAlertRequest
from falaai_api.models.create_webhook_request import CreateWebhookRequest as CreateWebhookRequest
from falaai_api.models.diagnostic_analysis_map import DiagnosticAnalysisMap as DiagnosticAnalysisMap
from falaai_api.models.diagnostic_audio_event import DiagnosticAudioEvent as DiagnosticAudioEvent
from falaai_api.models.diagnostic_categorical_analysis import DiagnosticCategoricalAnalysis as DiagnosticCategoricalAnalysis
from falaai_api.models.diagnostic_participant import DiagnosticParticipant as DiagnosticParticipant
from falaai_api.models.diagnostic_request import DiagnosticRequest as DiagnosticRequest
from falaai_api.models.diagnostic_response import DiagnosticResponse as DiagnosticResponse
from falaai_api.models.diagnostic_text_analysis import DiagnosticTextAnalysis as DiagnosticTextAnalysis
from falaai_api.models.diagnostic_usage import DiagnosticUsage as DiagnosticUsage
from falaai_api.models.email_alert_item import EmailAlertItem as EmailAlertItem
from falaai_api.models.email_alert_list_response import EmailAlertListResponse as EmailAlertListResponse
from falaai_api.models.email_alert_message_response import EmailAlertMessageResponse as EmailAlertMessageResponse
from falaai_api.models.email_event import EmailEvent as EmailEvent
from falaai_api.models.http_validation_error import HTTPValidationError as HTTPValidationError
from falaai_api.models.health_response import HealthResponse as HealthResponse
from falaai_api.models.location_inner import LocationInner as LocationInner
from falaai_api.models.message_response import MessageResponse as MessageResponse
from falaai_api.models.participant import Participant as Participant
from falaai_api.models.participant_diagnostic import ParticipantDiagnostic as ParticipantDiagnostic
from falaai_api.models.risk_audit_analysis_v2 import RiskAuditAnalysisV2 as RiskAuditAnalysisV2
from falaai_api.models.risk_audit_applied_action_v2 import RiskAuditAppliedActionV2 as RiskAuditAppliedActionV2
from falaai_api.models.risk_audit_audio_event_model_v2 import RiskAuditAudioEventModelV2 as RiskAuditAudioEventModelV2
from falaai_api.models.risk_audit_audit_decisions_v2 import RiskAuditAuditDecisionsV2 as RiskAuditAuditDecisionsV2
from falaai_api.models.risk_audit_conversation_scores_v2 import RiskAuditConversationScoresV2 as RiskAuditConversationScoresV2
from falaai_api.models.risk_audit_detection_item_v2 import RiskAuditDetectionItemV2 as RiskAuditDetectionItemV2
from falaai_api.models.risk_audit_detections_v2 import RiskAuditDetectionsV2 as RiskAuditDetectionsV2
from falaai_api.models.risk_audit_indexer_v2 import RiskAuditIndexerV2 as RiskAuditIndexerV2
from falaai_api.models.risk_audit_meta_v2 import RiskAuditMetaV2 as RiskAuditMetaV2
from falaai_api.models.risk_audit_participant_v2 import RiskAuditParticipantV2 as RiskAuditParticipantV2
from falaai_api.models.risk_audit_participants_v2 import RiskAuditParticipantsV2 as RiskAuditParticipantsV2
from falaai_api.models.risk_audit_request import RiskAuditRequest as RiskAuditRequest
from falaai_api.models.risk_audit_scores_v2 import RiskAuditScoresV2 as RiskAuditScoresV2
from falaai_api.models.risk_audit_scoring_explanation_v2 import RiskAuditScoringExplanationV2 as RiskAuditScoringExplanationV2
from falaai_api.models.risk_audit_summary_v2 import RiskAuditSummaryV2 as RiskAuditSummaryV2
from falaai_api.models.risk_audit_timeline_v2 import RiskAuditTimelineV2 as RiskAuditTimelineV2
from falaai_api.models.risk_audit_usage_v2 import RiskAuditUsageV2 as RiskAuditUsageV2
from falaai_api.models.risk_audit_v2 import RiskAuditV2 as RiskAuditV2
from falaai_api.models.risk_audit_v2_response import RiskAuditV2Response as RiskAuditV2Response
from falaai_api.models.risk_audit_verdict_v2 import RiskAuditVerdictV2 as RiskAuditVerdictV2
from falaai_api.models.transcription_response import TranscriptionResponse as TranscriptionResponse
from falaai_api.models.transcription_usage import TranscriptionUsage as TranscriptionUsage
from falaai_api.models.update_email_alert_request import UpdateEmailAlertRequest as UpdateEmailAlertRequest
from falaai_api.models.update_webhook_request import UpdateWebhookRequest as UpdateWebhookRequest
from falaai_api.models.usage_by_key_item import UsageByKeyItem as UsageByKeyItem
from falaai_api.models.usage_log_item import UsageLogItem as UsageLogItem
from falaai_api.models.usage_log_response import UsageLogResponse as UsageLogResponse
from falaai_api.models.validation_error import ValidationError as ValidationError
from falaai_api.models.version_response import VersionResponse as VersionResponse
from falaai_api.models.webhook_event import WebhookEvent as WebhookEvent
from falaai_api.models.webhook_item import WebhookItem as WebhookItem
from falaai_api.models.webhook_list_response import WebhookListResponse as WebhookListResponse
from falaai_api.models.whatsapp_conversation import WhatsappConversation as WhatsappConversation
from falaai_api.models.whatsapp_conversations_response import WhatsappConversationsResponse as WhatsappConversationsResponse
from falaai_api.models.whatsapp_meta import WhatsappMeta as WhatsappMeta
from falaai_api.models.whatsapp_speaker import WhatsappSpeaker as WhatsappSpeaker
from falaai_api.models.whatsapp_usage import WhatsappUsage as WhatsappUsage

